# This is a TOML document
# For more information on TOML, visit https://github.com/toml-lang/toml

[project]
name = "Ct_PD_Scraper"
description = "Scraper which puts data from the Republican-American police blotter into a database"
version = "0.3.0"
updated = 2020-02-20
author = "David A"

[data]
path = "./data"

[env]
path = "."

[prev_links]
link_file = "scraped_links.json"

[login]
url = "https://www.rep-am.com/login"

	[login.headers]
	Host = "www.rep-am.com"
	User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
	Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
	Accept-Language = "en-US,en;q=0.5"
	Accept-Encoding = "gzip, deflate, br"
	Referer = "https://www.rep-am.com/login"
	Content-Type = "application/x-www-form-urlencoded"
	Origin = "https://www.rep-am.com"
	DNT = "1"
	Connection = "keep-alive"
	Upgrade-Insecure-Requests = "1"
	TE = "Trailers"

[session]
base_url = "https://www.rep-am.com/category/local/records/police/"
base_pages = "1"

	[session.headers]
	Host = "www.rep-am.com"
	User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0"
	Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
	Accept-Language = "en-US,en;q=0.5"
	Accept-Encoding = "gzip, deflate, br"
	DNT = "1"
	Connection = "keep-alive"
	Upgrade-Insecure-Requests = "1"
	TE = "Trailers"

[database]
inserter = "mysql"

	[database.config.sqlite]
		database = "pd.db"

	[database.config.mysql]
		# user =   # Uncomment to add value
		# database =  # Uncomment to add value
		# password =  # Uncomment to add value


		# port = # Uncomment to add value
		# charset = # Uncomment to add value
		# client_flag = # Uncomment to add value
		# connect_timeout = # Uncomment to add value
		# autocommit = # Uncomment to add value
		# local_infile = # Uncomment to add value
		# defer_connect = # Uncomment to add value
		# binary_prefix = # Uncomment to add value
		# read_default_file =  # Uncomment to add value
		# conv =  # Uncomment to add value
		# host =  # Uncomment to add value
		# unix_socket =  # Uncomment to add value
		# sql_mode =  # Uncomment to add value
		# use_unicode =  # Uncomment to add value
		# ssl =  # Uncomment to add value
		# init_command =  # Uncomment to add value
		# read_default_group =  # Uncomment to add value
		# compress =  # Uncomment to add value
		# named_pipe =  # Uncomment to add value
		# auth_plugin_map =  # Uncomment to add value
		# read_timeout =  # Uncomment to add value
		# write_timeout =  # Uncomment to add value
		# bind_address =  # Uncomment to add value
		# program_name =  # Uncomment to add value
		# server_public_key =  # Uncomment to add value


		# cursorclass = Cursor  # Change this with **kwargs
		# max_allowed_packet = 16*1024*1024  # Change this with **kwargs

[cleaning]
cleaner = "basic"